// This file is regenerated by tools/sync-zebrabyte-blog.mjs before every production build.
// Keeping an empty committed placeholder makes local type-checking and first-run builds deterministic.
export const legacyWixBlogRedirects: Readonly<Record<string, string>> = Object.freeze({});
