// Generated by tools/sync-zebrabyte-blog-v2.mjs. Do not edit manually.
export const legacyWixBlogRedirects: Readonly<Record<string, string>> = Object.freeze({
  "4-adevaruri-surprinzatoare-pe-care-o-pana-masiva-de-internet-ni-le-a-dezvaluit-despre-lumea-noas-27": "4-adevaruri-surprinzatoare-pe-care-o-pana-masiva-de-internet-ni-le-a-dezvaluit-despre-lumea-noas",
  "avertizare-actualizati-de-urgenta-aplicatiile-de-tip-browser-bazate-pe-chromium-29": "avertizare-actualizati-de-urgenta-aplicatiile-de-tip-browser-bazate-pe-chromium",
  "cel-mai-mare-data-leak-din-istorie-iunie-2025-8": "cel-mai-mare-data-leak-din-istorie-iunie-2025",
  "cele-mai-frecvente-amenintari-cibernetice-in-domeniul-gazduirii-web-26": "cele-mai-frecvente-amenintari-cibernetice-in-domeniul-gazduirii-web",
  "cve-2025-8088-cum-romcom-a-exploatat-o-vulnerabilitate-zero-day-in-winrar-detalii-impact-si-reco-16": "cve-2025-8088-cum-romcom-a-exploatat-o-vulnerabilitate-zero-day-in-winrar-detalii-impact-si-reco",
  "de-ce-modelul-zero-trust-este-esential-pentru-hostingul-securizat-in-2025-7": "de-ce-modelul-zero-trust-este-esential-pentru-hostingul-securizat-in-2025",
  "de-ce-protectia-anti-malware-este-esentiala-pentru-orice-site-in-2025-9": "de-ce-protectia-anti-malware-este-esentiala-pentru-orice-site-in-2025",
  "de-ce-zebrabyte-este-alegerea-superioara-in-hosting-securitate-web-13": "de-ce-zebrabyte-este-alegerea-superioara-in-hosting-securitate-web",
  "identitatea-digitala-in-marea-britanie-lansarea-britcard-in-2025-o-revolutie-sau-o-amenintare-20": "identitatea-digitala-in-marea-britanie-lansarea-britcard-in-2025-o-revolutie-sau-o-amenintare",
  "inteligenta-artificiala-si-atacurile-cibernetice-o-noua-era-a-amenintarilor-digitale-2025-19": "inteligenta-artificiala-si-atacurile-cibernetice-o-noua-era-a-amenintarilor-digitale-2025",
  "legea-232-2022-noutati-in-accesibilitatea-digitala-pentru-producatori-si-furnizori-de-servicii-12": "legea-232-2022-noutati-in-accesibilitatea-digitala-pentru-producatori-si-furnizori-de-servicii",
  "misconfigured-not-malicious-lectiile-din-scurgerea-obr-30": "misconfigured-not-malicious-lectiile-din-scurgerea-obr",
  "mitre-si-programul-cve-ce-se-intampla-dupa-expirarea-contractului-din-16-aprilie-2025-6": "mitre-si-programul-cve-ce-se-intampla-dupa-expirarea-contractului-din-16-aprilie-2025",
  "securitatea-campaniilor-google-ads-cum-sa-opresti-fermele-de-boti-care-acceseaza-linkurile-utm-s-25": "securitatea-campaniilor-google-ads-cum-sa-opresti-fermele-de-boti-care-acceseaza-linkurile-utm-s",
  "vulnerabilitate-instagram-postari-private-expuse-fara-autentificare-33": "vulnerabilitate-instagram-postari-private-expuse-fara-autentificare",
  "vulnerabilitati-in-tema-flatsome-cum-exploateaza-atacurile-cu-boti-temele-wordpress-neactualizat-24": "vulnerabilitati-in-tema-flatsome-cum-exploateaza-atacurile-cu-boti-temele-wordpress-neactualizat"
});
