// Generated by tools/sync-sanity-site.mjs during the website build.
// The checked-in empty fallback keeps standalone Worker tooling resolvable before a content sync.
export const cmsManagedRoutes = new Set<string>([]);
